itdblib/frontend/views/asset_consume.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: wangzq <wangzhenqing1008@163.com>

from flask import (
    request,
    Blueprint,
    render_template,
    send_file,
    session,
    make_response
)
import os
from qg.core import log as logging
from itdblib.common import ajax
from itdblib.services.asset_consume_service import AssetConsumeService
from itdblib.common.asset_info_utils import AssetInfoUtils

LOG = logging.getLogger(__name__)

bp = Blueprint('asset_consume', __name__)


@bp.route('/asset/consume', methods=['POST'])
def show_asset_info():
    start = request.form['iDisplayStart']
    count = request.form['iDisplayLength']
    acs = AssetConsumeService()
    return acs.get_asset_consume_info_all_show(start, count)


@bp.route('/asset_consume', methods=['GET', 'POST'])
def assetConsume():
    return render_template('asset_consume.html', pageTitle=u'耗材管理')


@bp.route('/consume/num', methods=['POST'])
def get_consume_num():
    params = request.form
    acs = AssetConsumeService()
    return acs.get_prov_model_place_num(params)


@bp.route('/consume/<id>', methods=['POST'])
def show_asset_phone_info_by_all(id):
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    acs = AssetConsumeService()
    return acs.get_asset_consume_info_search_show(id, start, count)


@bp.route('/operate/<consume_id>', methods=['GET'])
def get_operate_infos(consume_id):
    from itdblib.dal.operation_info_dal import OperationInfoDal

    operInfos = OperationInfoDal().get_all_oper_info_by_asset_id(consume_id)
    aps = AssetConsumeService()
    return aps.get_consume_operate_json(operInfos)


@bp.route('/consume/id/<consume_id>', methods=['GET'])
def show_asset_consume_info_by_id(consume_id):
    acs = AssetConsumeService()
    return acs.get_asset_consume_info_by_id(consume_id)


@bp.route('/consume/out', methods=['POST'])
def add_old_asset_info():
    params = request.form
    operator = session.get('rtx_id')
    ret = AssetConsumeService().store_out_add_consume_data(params, operator)
    if ret:
        msg = u"已有耗材类数据出库成功"
        LOG.info(msg)
        return ajax.api_success(msg=msg, data=[])
    else:
        msg = u"已有耗材类数据出库失败"
        LOG.error(msg)
        return ajax.api_error(msg=msg)


@bp.route('/consume/advanced', methods=['POST'])
def show_advanced_asset_info():
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    acs = AssetConsumeService()
    params = request.values
    return acs.get_asset_consume_info_advanced_search_show(params, start, count)


@bp.route('/old/add', methods=['POST'])
def store_consume_old_data():
    data = request.form
    ret, msg = AssetConsumeService().store_consume_old_add_data(data)
    if ret:
        LOG.info(msg)
        return ajax.api_success(msg=msg, data=[])
    else:
        LOG.error(msg)
        return ajax.api_error(msg=msg)


@bp.route('/export/asset', methods=['POST', 'GET'])
def export_asset_info():
    key = request.form['exportData']
    from itdblib.common.xls_utils import writeExcel

    aiu = AssetInfoUtils()
    chlist = aiu.output_consume_excel_ch_list()
    enlist = aiu.output_consume_excel_en_list()
    params = AssetConsumeService().get_export_excel_data(key)
    save_file = writeExcel(params, '耗材类结果数据.xls', chlist, enlist)
    response = make_response(send_file(save_file,
                                       as_attachment=True
                                       ))
    filesize = os.path.getsize(save_file)
    response.headers['Content-Length'] = filesize
    os.remove(save_file)
    return response

itdblib/frontend/views/asset_manager.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: wangzq <wangzhenqing1008@163.com>

from flask import (
    Blueprint,
    render_template,
    request,
    send_file,
    make_response
)
from qg.core import log as logging
import os
from itdblib.services.asset_manager_service import AssetManagerService
from itdblib.services.asset_info_service import AssetInfoService
from itdblib.common import ajax
from itdblib.dal.asset_info_dal import AssetInfoDal
from itdblib.common.asset_info_utils import AssetInfoUtils

LOG = logging.getLogger(__name__)

bp = Blueprint('asset_manager', __name__)


@bp.route('/asset_manager', methods=['GET'])
def assetManager():
    return render_template("asset_manager.html", pageTitle=u'资产管理')


@bp.route('/asset', methods=['POST'])
def show_asset_info():
    start = request.form['iDisplayStart']
    count = request.form['iDisplayLength']
    print request.form
    ams = AssetManagerService()
    return ams.get_asset_info_all_show(start, count)


@bp.route('/asset/<id>', methods=['POST'])
def show_asset_info_by_all(id):
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    ams = AssetManagerService()
    return ams.get_asset_info_search_show(id, start, count)


@bp.route('/asset/advanced', methods=['POST'])
def show_advanced_asset_info():
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    ams = AssetManagerService()
    params = request.values
    return ams.get_asset_info_advanced_search_show(params, start, count)


@bp.route('/asset/id/<asset_id>', methods=['GET'])
def show_asset_info_by_id(asset_id):
    ais = AssetManagerService()
    return ais.get_asset_info_by_asset_id(asset_id)


@bp.route('/operate/<asset_id>', methods=['GET'])
def get_operate_infos(asset_id):
    from itdblib.dal.operation_info_dal import OperationInfoDal

    operInfos = OperationInfoDal().get_all_oper_info_by_asset_id(asset_id)
    ams = AssetManagerService()
    return ams.get_asset_operate_json(operInfos)


@bp.route('/edit_asset', methods=['POST'])
def submit_asset_info():
    try:
        params = request.form
        ams = AssetManagerService()
        ret, msg = ams.store_edit_asset_info_data(params)
        if ret:
            LOG.info(msg)
            return ajax.api_success(msg=msg, data=[])
        else:
            LOG.error(msg)
            return ajax.api_error(msg=msg)
    except Exception, _ex:
        LOG.error("error occured while submit_asset_info : %s" % str(_ex))
        return u"编辑失败"


@bp.route('/export/asset', methods=['POST', 'GET'])
def export_asset_info():
    key = request.form['exportData']
    from itdblib.common.xls_utils import writeExcel

    aiu = AssetInfoUtils()
    chlist = aiu.output_excel_ch_list()
    enlist = aiu.output_excel_en_list()
    params = AssetManagerService().get_export_excel_data(key)
    save_file = writeExcel(params, '固定资产类结果数据.xls', chlist, enlist)
    response = make_response(send_file(save_file,
                                       as_attachment=True
                            ))
    filesize = os.path.getsize(save_file)
    response.headers['Content-Length'] = filesize
    os.remove(save_file)
    return response

itdblib/frontend/views/asset_phone.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: wangzq <wangzhenqing1008@163.com>

from flask import (
    request,
    Blueprint,
    session,
    render_template,
    make_response,
    send_file
)
from qg.core import log as logging
from itdblib.common import ajax
from itdblib.services.asset_phone_service import AssetPhoneService
from itdblib.dal.asset_phone_info_dal import AssetPhoneInfoDal
from itdblib.common.asset_info_utils import AssetInfoUtils

import os

LOG = logging.getLogger(__name__)

bp = Blueprint('asset_phone', __name__)


@bp.route('/asset/phone', methods=['POST'])
def show_asset_phone_info():
    start = request.form['iDisplayStart']
    count = request.form['iDisplayLength']
    aps = AssetPhoneService()
    return aps.get_asset_phone_info_all_show(start, count)


@bp.route('/asset_phone', methods=['GET', 'POST'])
def assetPhone():
    return render_template('asset_phone.html', pageTitle=u'号码管理')


@bp.route('/phone/<id>', methods=['POST'])
def show_asset_phone_info_by_all(id):
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    aps = AssetPhoneService()
    return aps.get_asset_phone_info_search_show(id, start, count)


@bp.route('/phone/id/<phone_no>', methods=['GET'])
def show_asset_phone_info_by_id(phone_no):
    aps = AssetPhoneService()
    return aps.get_asset_phone_info_by_id(phone_no)


@bp.route('/operate/<phone_no>', methods=['GET'])
def get_operate_infos(phone_no):
    from itdblib.dal.operation_info_dal import OperationInfoDal

    operInfos = OperationInfoDal().get_all_oper_info_by_asset_id(phone_no)
    aps = AssetPhoneService()
    return aps.get_phone_operate_json(operInfos)


@bp.route('/phone/advanced', methods=['POST'])
def show_advanced_asset_info():
    start = request.values['iDisplayStart']
    count = request.values['iDisplayLength']
    aps = AssetPhoneService()
    params = request.values
    return aps.get_asset_phone_info_advanced_search_show(params, start, count)


@bp.route('/old/add', methods=['POST'])
def store_phone_old_data():
    data = request.form
    print data
    ret, msg = AssetPhoneService().store_phone_old_add_data(data)
    if ret:
        LOG.info(msg)
        return ajax.api_success(msg=msg, data=[])
    else:
        LOG.error(msg)
        return ajax.api_error(msg=msg)


@bp.route('/out', methods=['POST'])
def get_required_out_data():
    data = request.form
    return AssetPhoneService().get_phone_out_data(data)


@bp.route('/out/data', methods=['POST'])
def store_phone_out_data():
    data = request.form
    operator = session.get('rtx_id')
    ret, msg = AssetPhoneService().store_phone_out_data(data, operator)
    if ret:
        LOG.info(msg)
        return ajax.api_success(msg=msg, data=[])
    else:
        LOG.error(msg)
        return ajax.api_error(msg=msg)


@bp.route('/export/asset', methods=['POST', 'GET'])
def export_asset_info():
    key = request.form['exportData']
    from itdblib.common.xls_utils import writeExcel

    aiu = AssetInfoUtils()
    chlist = aiu.output_phone_excel_ch_list()
    enlist = aiu.output_phone_excel_en_list()
    params = AssetPhoneService().get_export_excel_data(key)
    save_file = writeExcel(params, '电话号码类结果数据.xls', chlist, enlist)
    response = make_response(send_file(save_file,
                                       as_attachment=True
                            ))
    filesize = os.path.getsize(save_file)
    response.headers['Content-Length'] = filesize
    os.remove(save_file)
    return response

itdblib/frontend/views/attribute_manager.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: wangzq <wangzhenqing1008@163.com>

import json

from flask import (
    Blueprint,
    render_template,
    request,
)
from qg.core import log as logging
from itdblib.services.attribute_manager_service import AttributeManagerService
from itdblib.common import ajax

LOG = logging.getLogger(__name__)

bp = Blueprint('attribute_manager', __name__)


@bp.route('/attribute_manager', methods=['GET', 'POST'])
def attributeManager():
    return render_template('attribute_manager.html', pageTitle=u'设备管理')


@bp.route('/load_device_type_lists', methods=['POST', 'GET'])
def deviceTypeLists():
    deviceList = []
    try:
        deviceList = AttributeManagerService().get_all_devices()
        return json.dumps(deviceList)
    except Exception, _ex:
        LOG.error("get all device provider model is error: %s"
                 % str(_ex))
        return json.dumps(deviceList)


@bp.route('/add_device_type', methods=['POST'])
def addDeviceType():
    try:
        data = request.form
        dataNew = {}
        for k, v in data.items():
            dataNew[k] = v
        bFlag, strRet = AttributeManagerService().addDeviceTypeInfos(dataNew)
        if bFlag:
            return ajax.api_success(msg=strRet, data=[])
        else:
            return ajax.api_error(msg=strRet)
    except Exception, _ex:
        LOG.error("error occured while add device type: %s" % str(_ex))
        return ajax.api_error(msg=u'添加失败')


@bp.route('/add_asset_class_infos', methods=['POST'])
def addAssetClass():
    try:
        data = request.form
        dataNew = {}
        for k, v in data.items():
            dataNew[k] = v
        num, msg = AttributeManagerService().addAssetClass(dataNew)
        if -1 == num:
            LOG.error("添加错误")
            return ajax.api_error(msg=msg)
        elif 0 == num:
            return ajax.api_success(msg=msg, data=False)
        else:
            return ajax.api_success(msg=msg)
    except Exception as _ex:
        LOG.error("error occured while add asset tree node: %s" % str(_ex))
        return ajax.api_error(msg=u'添加失败')


@bp.route('/remove_asset_class_node', methods=['POST'])
def removeAssetClassNode():
    try:
        data = request.form
        dataNew = {}
        for k, v in data.items():
            dataNew[k] = v
        bFlag = AttributeManagerService().removeAssetClassNode(dataNew)
        if bFlag:
            return ajax.api_error(msg=u'删除失败')
        return ajax.api_success(msg=u"删除成功", data=[])
    except Exception as _ex:
        LOG.error("error occured while remvoe asset tree node: %s" % str(_ex))
        return ajax.api_error(msg=u'删除失败')


@bp.route('/load_store_house_infos', methods=['POST', 'GET'])
def loadStoreHouseInfos():
    storeList = []
    try:
        storeList = AttributeManagerService().get_all_store_place_infos()
        return json.dumps(storeList)
    except Exception, _ex:
        LOG.error("get all storehouse infos is error: %s"
                 % str(_ex))
        return json.dumps(storeList)


@bp.route('/add_store_place', methods=['POST'])
def addStorehouseMsgs():
    try:
        data = request.form
        print data
        bFlag, msg = AttributeManagerService().addStorePlace(data)
        if bFlag:
            return ajax.api_success(msg=msg, data=[])
        else:
            return ajax.api_error(msg=msg)
    except Exception as _ex:
        LOG.error("error occured while add storehouse msgs: %s" % str(_ex))
        return ajax.api_error(msg=u'添加失败')

itdblib/frontend/views/stock_in.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: wangzq <wangzhenqing1008@163.com>

import os
import json

from flask import (
    Blueprint,
    render_template,
    request,
    session
)
from werkzeug.utils import secure_filename
from qg.core import log as logging

from itdblib.common.parse_excel import get_excel_sheet_name
from itdblib.common import ajax
from itdblib.services.stock_in_service import StockInService
from itdblib.services.asset_consume_service import AssetConsumeService

LOG = logging.getLogger(__name__)

bp = Blueprint('stock_in', __name__)

@bp.route('/stock_in', methods=['GET', 'POST'])
def stockIn():
    return render_template('stock_in.html', pageTitle=u'入库')


@bp.route('/asset/types', methods=['POST'])
def get_asset_type_list():
    num = request.form['return_val']
    num = int(num)
    return StockInService().get_asset_type_list(num)


@bp.route('/new/add', methods=['POST'])
def add_new_asset_info():
    # try:
    data = request.form
    sis = StockInService()
    new_data = {}
    for k, v in data.items():
        new_data[k] = v
    ret, msg = sis.add_new_asset_info(new_data)
    return json.dumps(dict(msg=msg, success=ret))
    # if ret:
    # return ajax.api_success(msg=u'添加成功', data=[])
    # else:
    # LOG.error(msg)
    # return ajax.api_error(msg=msg)
    # except Exception as _ex:
    #     LOG.error("error occured while add_new_asset_info : %s" % str(_ex))
    #     return ajax.api_error(msg=u'添加失败')


@bp.route('/upload_asset_file', methods=['POST'])
def upload_asset_file():
    try:
        f = request.files.get("file")
        if not f:
            return ajax.api_error(msg=u'没有获取文件信息')
        fileName = secure_filename(f.filename)
        path = '/tmp/'
        fileFullPath = os.path.join(path, fileName)
        # import re
        # temp = tempfile.mkdtemp(suffix='xlsx', prefix='asset', dir=fileFullPath)
        # os.rename(os.path.join(path, fileName), os.path.join(path, new_name))
        f.save(fileFullPath)
        ret, msg = get_excel_sheet_name(fileFullPath)
        if not ret:
            return ajax.api_error(msg=msg)
        else:
            operator = session.get('rtx_id')
            ss = StockInService()
            ret, msg = ss.muti_stock_in_different_assets(fileFullPath, operator, int(msg))
            if ret:
                return ajax.api_success(msg=msg, data=[])
            else:
                return ajax.api_error(msg=msg)
    except Exception, _ex:
        LOG.error("error occured while upload_asset_file : %s" % str(_ex))
        return ajax.api_error(msg=u'添加失败')


@bp.route('/consume/num', methods=['POST'])
def get_consume_num():
    params = request.form
    acs = AssetConsumeService()
    return str(acs.get_prov_model_place_num(params))


@bp.route('/consume/use_num', methods=['POST'])
def get_consume_in_num():
    params = request.form
    acs = AssetConsumeService()
    params = acs.get_prov_model_user_name_num(params)
    return params

itdblib/frontend/templates/blank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>ITDB - {{ pageTitle }}</title>

    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- basic styles -->

    <link href="{{static_url}}/ace/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/jquery-ui-1.10.3.full.min.css"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/chosen.css"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/jquery.gritter.css"/>

    <!--[if IE 7]>
    <link rel="stylesheet" href="{{static_url}}/ace/css/font-awesome-ie7.min.css"/>
    <![endif]-->

    <!-- page specific plugin styles -->

    <!-- ace styles -->

    <link rel="stylesheet" href="{{static_url}}/ace/css/ace.min.css"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/ace-rtl.min.css"/>
    <link rel="stylesheet" href="{{static_url}}/ace/css/ace-skins.min.css"/>

    <!--[if lte IE 8]>
    <link rel="stylesheet" href="{{static_url}}/ace/css/ace-ie.min.css"/>
    <![endif]-->

    <!-- inline styles related to this page -->

    <!-- ace settings handler -->

    <script src="{{static_url}}/ace/js/ace-extra.min.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

    <!--[if lt IE 9]>
    <script src="{{static_url}}/ace/js/html5shiv.js"></script>
    <script src="{{static_url}}/ace/js/respond.min.js"></script>
    <![endif]-->
    {% block header %}
    {% endblock %}

    <style type="text/css">
        body {
            font-family: Arial, 'Times New Roman', 'Microsoft YaHei', SimSun;
        }
    </style>
</head>

<body>
{% include "header.html"%}
<div class="main-container" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.check('main-container', 'fixed')
        } catch (e) {
        }
    </script>

    <div class="main-container-inner">
        <a class="menu-toggler" id="menu-toggler" href="#">
            <span class="menu-text"></span>
        </a>

        <div class="sidebar" id="sidebar">
            <script type="text/javascript">
                try {
                    ace.settings.check('sidebar', 'fixed')
                } catch (e) {
                }
            </script>

            <ul class="nav nav-list">
                <li
                {% if request.blueprint == 'index' %}class="active"{% endif %}>
                <a href="{{url_for('index.index')}}">
                    <i class="icon-home"></i>
                    <span class="menu-text">首页</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'stock_in'%}class="active"{% endif %}>
                <a href="{{url_for('stock_in.stockIn')}}">
                    <i class="icon-edit"></i>
                    <span class="menu-text">入库</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'stock_out'%}class="active"{% endif %}>
                <a href="{{url_for('stock_out.stockOut')}}">
                    <i class="icon-share-alt"></i>
                    <span class="menu-text">出库</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'asset_manager'%}class="active"{% endif %}>
                <a href="{{url_for('asset_manager.assetManager')}}">
                    <i class="icon-cogs"></i>
                    <span class="menu-text">资产管理</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'asset_consume'%}class="active"{% endif %}>
                <a href="{{url_for('asset_consume.assetConsume')}}">
                    <i class="icon-leaf"></i>
                    <span class="menu-text">耗材管理</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'asset_phone'%}class="active"{% endif %}>
                <a href="{{url_for('asset_phone.assetPhone')}}">
                    <i class="icon-key"></i>
                    <span class="menu-text">号码管理</span>
                </a>
                </li>

                <li
                {% if request.blueprint == 'attribute_manager'%}class="active"{% endif %}>
                <a href="{{url_for('attribute_manager.attributeManager')}}">
                    <i class="icon-cog"></i>
                    <span class="menu-text">属性管理</span>
                </a>
                </li>

            </ul>
            <!-- /.nav-list -->

            <div class="sidebar-collapse" id="sidebar-collapse">
                <i class="icon-double-angle-left" data-icon1="icon-double-angle-left"
                   data-icon2="icon-double-angle-right"></i>
            </div>

            <script type="text/javascript">
                try {
                    ace.settings.check('sidebar', 'collapsed')
                } catch (e) {
                }
            </script>
        </div>

        <div class="main-content">
            <div class="breadcrumbs" id="breadcrumbs">
                <script type="text/javascript">
                    try {
                        ace.settings.check('breadcrumbs', 'fixed')
                    } catch (e) {
                    }
                </script>

                <ul class="breadcrumb">
                    <li>
                        <i class="icon-home home-icon"></i>
                        <a href="{{url_for('index.index')}}">首页</a>
                    </li>
                    <li class="active">{{ pageTitle }}</li>
                </ul>
                <!-- .breadcrumb -->

            </div>
            <div class="page-content">
                <!-- PAGE CONTENT BEGINS -->
                {% block body %} {% endblock %}
                <!-- PAGE CONTENT ENDS -->
            </div>
            <!-- /.page-content -->
        </div>
        <!-- /.main-content -->
    </div>
    <!-- /.main-container-inner -->

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>
</div>
<!-- /.main-container -->

<!-- basic scripts -->

<!--[if !IE]> -->
<script src="{{static_url}}/ace/js/jquery-2.0.3.min.js"></script>
<!-- <script src="{{static_url}}/ace/js/jquery-ui-1.10.3.full.min.js"></script>-->
<script src="{{static_url}}/ace/js/chosen.jquery.min.js"></script>
<!-- <![endif]-->
<!--[if IE]>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<![endif]-->

<!--[if !IE]> -->

<script type="text/javascript">
    window.jQuery || document.write("<script src='{{static_url}}/ace/js/jquery-2.0.3.min.js'>" + "<" + "/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='/static/js/jquery-1.10.2.min.js'>" + "<" + "/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if ("ontouchend" in document) document.write("<script src='{{static_url}}/ace/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
</script>
<script src="{{static_url}}/ace/js/bootstrap.min.js"></script>
<script src="{{static_url}}/ace/js/typeahead-bs2.min.js"></script>

<!-- page specific plugin scripts -->
<script src="{{static_url}}/ace/js/jquery.sparkline.min.js"></script>

<!-- ace scripts -->

<script src="{{static_url}}/ace/js/ace-elements.min.js"></script>
<script src="{{static_url}}/ace/js/ace.min.js"></script>
<script src="{{static_url}}/ace/js/jquery.gritter.min.js"></script>
<script src="{{static_url}}/ace/js/jquery.validate.min.js"></script>
<!-- inline scripts related to this page -->
{% block js %}
{% endblock %}

</body>
</html>

itdblib/frontend/templates/header.html
<div class="navbar navbar-default" id="navbar">
    <script type="text/javascript">
        try{ace.settings.check('navbar' , 'fixed')}catch(e){}
    </script>

    <div class="navbar-container" id="navbar-container">
        <div class="pull-left" style="color: white; font-size: 18px; padding: 9px">
                <small>
                    <i class="icon-cloud"></i>
                    ITDB
                </small>
        </div>

        <div class="pull-right" style="color: white; font-size: 16px; padding: 10px">
            <i class="icon-user"></i>
            <span>
                {{current_user}}&nbsp
            </span>

            <a href="{{url_for('index.logout', ret=request.url)}}" style="color: white; font-size: 16px">
                <i class="icon-off"></i>
                注销
            </a>
        </div>
    </div>
</div>